# Generated by Django 2.0.3 on 2018-03-13 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180313_1907'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-pub_date'], 'permissions': (('can_delete', 'Can delete the posts'),)},
        ),
    ]
